name: notes
services:
  database:
    container_name: database
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - './Database/init.sql:/docker-entrypoint-initdb.d/1.sql'

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: notes
      WAIT_HOSTS: database:3306

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

volumes:
  db_data:
