name: notes
services:
  database:
    container_name: database
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/1.sql

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DATABASE_URL: 'mysql://root:1234@database:3306/notes'
      SECRET_KEY: 464655b6c8702e2135daa64f1bb6f5df0c41dc6437c49555fdc7c0fd1c4a0160
      JWT_SECRET: f5da8e72fe05f14d527aa11a5010dc9aacd70d96023fab49427f1812dc4a9942
      WAIT_HOSTS: database:3306

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

volumes:
  database:
