name: notes
services:
  database:
    container_name: database
    image: mariadb:latest
    env_file: .env
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - '3306:3306'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    container_name: backend
    image: ghcr.io/jonathanxdr/notes-backend:latest
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    container_name: frontend
    image: ghcr.io/jonathanxdr/notes-frontend:latest
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

volumes:
  database:
