name: notes
services:
  database:
    container_name: database
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/1.sql

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DATABASE_URL: '${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}'
      # Auth
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      # Misc
      WAIT_HOSTS: database:3306

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

volumes:
  database:
