name: notes
services:
  traefik:
    image: traefik:latest
    command:
      - '--providers.docker=true'
      - '--entrypoints.default.address=:80'
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  database:
    container_name: database
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_PORT: ${DATABASE_PORT}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  backend:
    container_name: backend
    image: ghcr.io/jonathanxdr/notes-backend:latest
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DATABASE_URL: '${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}'
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      WAIT_HOSTS: database:3306
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=PathPrefix(`/api`)'
      - 'traefik.http.routers.backend.entrypoints=default'
      - 'traefik.http.services.backend.loadbalancer.server.port=3000'
      - 'traefik.http.routers.backend.priority=2'
    networks:
      - default

  frontend:
    container_name: frontend
    image: ghcr.io/jonathanxdr/notes-frontend:latest
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.frontend.entrypoints=default'
      - 'traefik.http.services.frontend.loadbalancer.server.port=3001'
      - 'traefik.http.routers.frontend.priority=1'
    networks:
      - default

volumes:
  database:

networks:
  default:
