apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./deployment
    kompose.version: 1.34.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.backend.entrypoints: default
    traefik.http.routers.backend.priority: "2"
    traefik.http.routers.backend.rule: PathPrefix(`/api`) || PathPrefix(`/swagger`)
    traefik.http.services.backend.loadbalancer.server.port: "3000"
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./deployment
        kompose.version: 1.34.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.backend.entrypoints: default
        traefik.http.routers.backend.priority: "2"
        traefik.http.routers.backend.rule: PathPrefix(`/api`) || PathPrefix(`/swagger`)
        traefik.http.services.backend.loadbalancer.server.port: "3000"
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: ://:@:/
            - name: JWT_SECRET
            - name: SECRET_KEY
            - name: WAIT_HOSTS
              value: database:3306
          image: ghcr.io/jonathanxdr/notes-backend:latest
          name: backend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
