apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jonathanxdr/notes-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: mariadb-url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: mariadb-name
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
