apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  mariadb-url: mariadb-service
  mariadb-name: notes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
data:
  notes.sql: |
    Drop database if exists notes;
    CREATE DATABASE IF NOT EXISTS `notes`;
    use notes;
    CREATE TABLE IF NOT EXISTS `notes`.`Categories` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `title` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    );
    CREATE TABLE IF NOT EXISTS `notes`.`Tasks` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `title` VARCHAR(45) NOT NULL,
        `description` VARCHAR(45) NOT NULL,
        `done` TINYINT NOT NULL,
        `category_id` INT NOT NULL REFERENCES `notes`.`Categories`(id),
        PRIMARY KEY (`id`)
    );
    INSERT INTO `notes`.`Categories` (`id`, `title`)
    VALUES (1, 'Category 1'),
        (2, 'Category 2'),
        (3, 'Category 3'),
        (4, 'Category 4'),
        (5, 'Category 5');
    INSERT INTO `notes`.`Tasks` (`title`, `description`, `done`, `category_id`)
    VALUES ('Task 1', 'Description 1', 0, 1),
        ('Task 2', 'Description 2', 0, 2),
        ('Task 3', 'Description 3', 0, 3),
        ('Task 4', 'Description 4', 0, 4),
        ('Task 5', 'Description 5', 0, 5);
