name: Deploy

on:
  workflow_run:
    workflows: ['publish']
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up WireGuard VPN
        uses: egor-tensin/setup-wireguard@v1.2.0
        with:
          endpoint: ${{ secrets.WIREGUARD_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WIREGUARD_ENDPOINT_PUBLIC_KEY }}
          ips: ${{ secrets.WIREGUARD_IPS }}
          allowed_ips: ${{ secrets.WIREGUARD_ALLOWED_IPS }}
          private_key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.LERNMAAS_IP }}
          username: ${{ secrets.LERNMAAS_USERNAME }}
          key: ${{ secrets.LERNMAAS_PRIVATE_KEY }}
          script: |
            set -e
            if [ -d M321 ]; then
              cd M321
              git fetch origin
              git checkout origin/main
              git reset --hard origin/main
            else
              git clone https://github.com/JonathanXDR/M321.git
              cd M321
            fi
            kubectl delete "$(kubectl api-resources --namespaced=true --verbs=delete -o name | tr "\n" "," | sed -e 's/,$//')" --all
            kubectl apply -f ./deployment
