name: Testing

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run ${{ matrix.service }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: frontend
            tag: ghcr.io/jonathanxdr/notes-frontend:latest
            token: GHCR_PAT_FRONTEND
          - service: backend
            tag: ghcr.io/jonathanxdr/notes-backend:latest
            token: GHCR_PAT_BACKEND

    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Git credentials for ${{ matrix.service }} submodule
        run: |
          git config --global url."https://${{ secrets[matrix.token] }}@github.com/".insteadOf "https://github.com/"

      - name: Initialize ${{ matrix.service }} submodule
        run: |
          git submodule update --init --recursive -- ${{ matrix.service }}
          git submodule foreach 'git fetch origin && git checkout origin/main && git reset --hard origin/main'

      - name: Run ${{ matrix.service }} tests
        run: |
          cd ${{ matrix.service }}
          npm ci
          npm run test
